
    create table tournament_player  (
        id bigint generated by default as identity,
        birthday date,
        email varchar(255),
        firstname varchar(255) not null,
        gender varchar(1),
        lastname varchar(255) not null,
        mobilenumber varchar(255),
        qttr integer,
        ttr integer,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity,
        avatar binary(255),
        email varchar(255),
        locale varchar(255),
        locked boolean not null,
        loginname varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        type integer,
        primary key (id)
    );

    create table user_role (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );
