INSERT INTO user (id, name, email, locked, loginname, password) VALUES (1, 'Peter Meier', 'pmeier@bla.de', 0, 'user', '42');
INSERT INTO user (id, name, email, locked, loginname, password) VALUES (2, 'Administrator', 'admin@bla.de', 0, 'admin', '42');
INSERT INTO user (id, name, email, locked, loginname, password) VALUES (3, 'Super User', 'superuser@bla.de', 0, 'superuser', '42');
INSERT INTO user (id, name, email, locked, loginname, password) VALUES (4, 'Fritz Müller', 'fritz@mueller.de', 0, 'user', '42');
INSERT INTO user (id, name, email, locked, loginname, password) VALUES (5, 'Karla Schweinchen', 'karla@gmx.net', 0, 'user', '42');
INSERT INTO user (id, name, email, locked, loginname, password) VALUES (6, 'Mauer Blümchen', 'mauer@blum.de', 0, 'user', '42');
INSERT INTO user (id, name, email, locked, loginname, password) VALUES (7, 'Valentino Rossi', 'rossi@rossi.it', 0, 'user', '42');
INSERT INTO user (id, name, email, locked, loginname, password) VALUES (8, 'Karl Foggarty', 'k@k.com', 0, 'user', '42');


INSERT INTO TOURNAMENT (ID, END_DATE, NAME, START_DATE) VALUES (1, '2015-06-03', 'Jitty Open 2015', '2015-06-01');
INSERT INTO TOURNAMENT (ID, END_DATE, NAME, START_DATE) VALUES (2, '2016-06-29', 'Jitty Open 2016', '2016-06-27');

INSERT INTO TOURNAMENT_CLASS (ID, T_ID, NAME, START_TIME, START_TTR, END_TTR, OPEN_FOR_MEN, OPEN_FOR_WOMEN, RUNNING) VALUES (1, 2, 'A-Klasse', NOW(), 1800, 3000, TRUE, FALSE, FALSE);
INSERT INTO TOURNAMENT_CLASS (ID, T_ID, NAME, START_TTR, END_TTR, OPEN_FOR_MEN, OPEN_FOR_WOMEN, RUNNING) VALUES (2, 2, 'B-Klasse', 0, 1850, TRUE, FALSE, FALSE);
INSERT INTO TOURNAMENT_CLASS (ID, T_ID, NAME, START_TTR, END_TTR, OPEN_FOR_MEN, OPEN_FOR_WOMEN, RUNNING) VALUES (3, 2, 'C-Klasse', 0, 1600, TRUE, FALSE, FALSE);
INSERT INTO TOURNAMENT_CLASS (ID, T_ID, NAME, START_TTR, END_TTR, OPEN_FOR_MEN, OPEN_FOR_WOMEN, RUNNING) VALUES (4, 2, 'D-Klasse', 0, 1400, TRUE, FALSE, FALSE);
INSERT INTO TOURNAMENT_CLASS (ID, T_ID, NAME, START_TTR, END_TTR, OPEN_FOR_MEN, OPEN_FOR_WOMEN, RUNNING) VALUES (5, 2, 'E-Klasse', 0, 1200, TRUE, FALSE, FALSE);

UPDATE USER SET TOURNAMENT_ID = 2 WHERE ID = 1;


INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (1, 'Badischer TTV', 'BaTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (2, 'Bayerischer TTV', 'BTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (3, 'Berliner TTV', 'BETTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (4, 'TTV Brandenburg', 'TTVB');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (5, 'FTT Bremen', 'FTTB');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (6, 'Hamburger TTV', 'Hamburger TTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (7, 'Hessischer TTV', 'HTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (8, 'TTV Mecklenburg-Vorpommern', 'TTVMV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (9, 'TTV Niedersachsen', 'TTVN');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (10, 'Pfälzischer TTV', 'PTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (11, 'Rheinhessischer TTV', 'RTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (12, 'TTV Rheinland', 'TTVR');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (13, 'Saarländischer TTB', 'STTB');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (14, 'Sächsischer TTV', 'STTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (15, 'TTV Sachsen-Anhalt', 'TTVSA');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (16, 'TTV Schleswig-Holstein', 'TTVSH');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (17, 'Südbadischer Tischtennis-Verband', 'SBTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (18, 'Thüringer TTV', 'TTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (19, 'TTV Württemberg-Hohenzollern', 'TTVWH');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (20, 'Westdeutscher TTV', 'WTTV');
INSERT INTO ASSOCIATION (ID, LONGNAME, SHORTNAME) VALUES (21, 'Ausland', 'Ausland');


INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('TV Scheven',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'WTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('TSV Eisenberg',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'TTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('SV Grambke Oslebshausen',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'FTTB'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('Ahlener SG',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'WTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('FC Ruthe',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'TTVN'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('Herpfer SV 07',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'TTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('Switzerland',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'Ausland'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('TTZ Altstadt-Kirkel',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'STTB'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('1. FC Bruchsal',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('1. TC Ittersbach',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('1. TTC Ketsch',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('ASV Eppelheim',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('ASV Grünwettersbach',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('BJC Buchen',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK 1927 Dossenheim',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Balzfeld',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Daxlanden',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Käfertal',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Mannheim Lindenhof',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Neckarhausen',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Ost Karlsruhe',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Rüppurr',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Schönau',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK St. Hildegard Käfertal Süd',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK St. Pius Neuostheim/Neuhermsheim',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Unterbalbach e.V. 1930',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));
INSERT INTO club(NAME,ASSOCIATION_ID) VALUES ('DJK Mannheim',(SELECT  id FROM ASSOCIATION WHERE SHORTNAME = 'BaTTV'));


INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (1, 'Timo', 'Boll', 'm', 1, 20, 2499, 2500);
INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (2, 'Palme', 'Saatkrähe', 'w', 2, 1, 1488, 1500);
INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (3, 'Kartoffel', 'Ohrentaucher', 'm', 3, 2, 1799, 1805);
INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (4, 'Noch', 'Keine Anmeldung', 'm', 4, 2, 1155, 1155);
INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (5, 'Ma', 'Long', 'm', 5, 2, 2400, 2400);
INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (6, 'Fan', 'Zhedong', 'm', 6, 2, 2299, 2299);
INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (7, 'Zhang', 'Jike', 'm', 7, 2, 2388, 2388);
INSERT INTO TOURNAMENT_PLAYER (ID, FIRSTNAME, LASTNAME, GENDER, CLUB_ID, ASSOCIATION_ID, QTTR, TTR) VALUES (7, 'Xu', 'Xin', 'm', 8, 2, 2399, 2399);

INSERT INTO TC_PLAYER (PLAYERS_ID, CLASSES_ID) VALUES (1, 1);
INSERT INTO TC_PLAYER (PLAYERS_ID, CLASSES_ID) VALUES (3, 1);
INSERT INTO TC_PLAYER (PLAYERS_ID, CLASSES_ID) VALUES (4, 1);
INSERT INTO TC_PLAYER (PLAYERS_ID, CLASSES_ID) VALUES (5, 1);
INSERT INTO TC_PLAYER (PLAYERS_ID, CLASSES_ID) VALUES (6, 1);
INSERT INTO TC_PLAYER (PLAYERS_ID, CLASSES_ID) VALUES (7, 1);
INSERT INTO TC_PLAYER (PLAYERS_ID, CLASSES_ID) VALUES (2, 2);