create table association (id bigint generated by default as identity (start with 1), longname varchar(255) not null, shortname varchar(255) not null, primary key (id));
CREATE TABLE club (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  click_tt_nr    VARCHAR(255),
  name           VARCHAR(255) NOT NULL,
  association_id BIGINT,
  PRIMARY KEY (id)
);
create table GAME_QUEUE (id bigint generated by default as identity (start with 1), primary key (id));
create table GAME_SET (id bigint generated by default as identity (start with 1), points1 integer, points2 integer, primary key (id));
create table GAME_TO_PLAYER (GAME_ID bigint not null, PLAYER_ID bigint not null);
create table group_phase (group_count integer, player_per_group integer, quali_group_count integer not null, id bigint not null, primary key (id));
create table ko_field (id bigint generated by default as identity (start with 1), NO_OF_ROUNDS integer, round_id bigint, primary key (id));
create table ko_phase (id bigint not null, KOFIELD_ID bigint, primary key (id));
CREATE TABLE Phase (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  S_ID   BIGINT,
  INDEXP INTEGER,
  PRIMARY KEY (id)
);
create table round (id bigint generated by default as identity (start with 1), GAME_SIZE integer, ROUND_TYPE integer, PREV_ROUND_ID bigint, primary key (id));
CREATE TABLE swiss_system_phase (
  MAX_ROUNDS INTEGER NOT NULL,
  ROUND      INTEGER NOT NULL,
  id         BIGINT  NOT NULL,
  group_id   BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE T_PLAYER (
  tournaments_id BIGINT NOT NULL,
  players_id     BIGINT NOT NULL,
  PRIMARY KEY (tournaments_id, players_id)
);
create table t_system (id bigint generated by default as identity (start with 1), TC_ID bigint, primary key (id));
create table TC_PLAYER (classes_id bigint not null, players_id bigint not null);
create table TG_PLAYER (TOURNAMENT_GROUP_ID bigint not null, PLAYER_ID bigint not null);
CREATE TABLE tournament (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  click_tt_id VARCHAR(255),
  end_date    DATE         NOT NULL,
  name        VARCHAR(255) NOT NULL,
  running     BOOLEAN      NOT NULL,
  start_date  DATE         NOT NULL,
  table_count INTEGER      NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE tournament_class (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  ACTIVE_PHASE   INTEGER      NOT NULL,
  age_group      VARCHAR(255) NOT NULL,
  end_ttr        INTEGER,
  max_age        DATE,
  min_age        DATE,
  name           VARCHAR(255) NOT NULL,
  open_for_men   BOOLEAN      NOT NULL,
  open_for_women BOOLEAN      NOT NULL,
  RUNNING        BOOLEAN      NOT NULL,
  start_ttr      INTEGER,
  START_TIME     TIMESTAMP,
  status         VARCHAR(255) NOT NULL,
  SYSTEM_TYPE    INTEGER      NOT NULL,
  T_ID           BIGINT,
  PRIMARY KEY (id)
);
create table tournament_group (id bigint generated by default as identity (start with 1), name varchar(10) not null, GP_ID bigint, primary key (id));
CREATE TABLE tournament_player (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  birthday             DATE,
  click_tt_internal_nr VARCHAR(255),
  click_tt_licence_nr  VARCHAR(255),
  email                VARCHAR(255),
  firstname            VARCHAR(255) NOT NULL,
  gender               VARCHAR(1),
  last_game_at         TIMESTAMP,
  lastname             VARCHAR(255) NOT NULL,
  mobilenumber         VARCHAR(255),
  qttr                 INTEGER,
  suspended            BOOLEAN,
  ttr                  INTEGER,
  association_id       BIGINT,
  club_id              BIGINT,
  PRIMARY KEY (id)
);
CREATE TABLE TOURNAMENT_SINGLE_GAME (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  called                BOOLEAN      NOT NULL,
  end_time              TIMESTAMP,
  NAME                  VARCHAR(255),
  played                BOOLEAN      NOT NULL,
  start_time            TIMESTAMP,
  table_no              INTEGER,
  tournament_class_name VARCHAR(255) NOT NULL,
  t_id                  BIGINT       NOT NULL,
  win_by_default        BOOLEAN,
  win_reason            INTEGER,
  winner                INTEGER      NOT NULL,
  GAME_QUEUE_ID         BIGINT,
  group_id              BIGINT,
  NEXT_GAME_ID          BIGINT,
  player1_id            BIGINT,
  player2_id            BIGINT,
  ROUND_ID              BIGINT,
  PRIMARY KEY (id)
);
create table TOURNAMENT_SINGLE_GAME_SET (TOURNAMENT_SINGLE_GAME_ID bigint not null, SETS_ID bigint not null);
create table user (id bigint generated by default as identity (start with 1), avatar varbinary(255), email varchar(255), locale varchar(255), locked boolean not null, loginname varchar(255) not null, name varchar(255) not null, password varchar(255) not null, type integer, TOURNAMENT_ID bigint, primary key (id));
create table user_role (id bigint generated by default as identity (start with 1), name varchar(255), primary key (id));
alter table association add constraint UK_ogdrfbju5finu018l8mvhdvug unique (longname);
alter table association add constraint UK_oqsncgu633nvys2yo9ehj7j14 unique (shortname);
ALTER TABLE TOURNAMENT_SINGLE_GAME_SET
  ADD CONSTRAINT UK_et5i78b8ngopb9nvxxw7dsurr UNIQUE (SETS_ID);
alter table club add constraint FKrft7ntsm4eurtpm0h9ng648vp foreign key (association_id) references association;
alter table GAME_TO_PLAYER add constraint FKk5bx3r6y9tw6719cky1xvpg80 foreign key (PLAYER_ID) references TOURNAMENT_SINGLE_GAME;
alter table GAME_TO_PLAYER add constraint FKca0r1lrsyhm231ja4fihlj789 foreign key (GAME_ID) references tournament_player;
alter table group_phase add constraint FKjofpwlrorhysm3ss9d18fya56 foreign key (id) references Phase;
alter table ko_field add constraint FK6i30o3c25tnnbcn18k38fan4c foreign key (round_id) references round;
alter table ko_phase add constraint FK8kotu3nslnrnh5yq6fj65x4jr foreign key (KOFIELD_ID) references ko_field;
alter table ko_phase add constraint FKfa55lj6k09jwffa7hghfihkof foreign key (id) references Phase;
ALTER TABLE Phase
  ADD CONSTRAINT FKb8sbbbk5ai0d5o0w1oiu2fcd0 FOREIGN KEY (S_ID) REFERENCES t_system;
alter table round add constraint FKhkndx0l8sli5r6gf7m0eveqn7 foreign key (PREV_ROUND_ID) references round;
alter table swiss_system_phase add constraint FK4p84g4b67qrf076pmupyq3psk foreign key (group_id) references tournament_group;
alter table swiss_system_phase add constraint FKghusqw84hup11ghej8i5ad9go foreign key (id) references Phase;
ALTER TABLE T_PLAYER
  ADD CONSTRAINT FKox4dt24cvyx5jdn4rs9lyeyk5 FOREIGN KEY (players_id) REFERENCES tournament_player;
ALTER TABLE T_PLAYER
  ADD CONSTRAINT FKmlaymevvua011spq8t5ke1tem FOREIGN KEY (tournaments_id) REFERENCES tournament;
alter table t_system add constraint FKer0y033wsm6ysyosohkxlykss foreign key (TC_ID) references tournament_class;
alter table TC_PLAYER add constraint FK996yua0ff90b7wx8m9mm0bqc7 foreign key (players_id) references tournament_player;
alter table TC_PLAYER add constraint FK9q89qmejhqft0x204goa1eg0n foreign key (classes_id) references tournament_class;
alter table TG_PLAYER add constraint FKlvtcmf9uuan17vu73lysr3afk foreign key (PLAYER_ID) references tournament_player;
alter table TG_PLAYER add constraint FK9euge99x86qrjlgl1cfn976ga foreign key (TOURNAMENT_GROUP_ID) references tournament_group;
alter table tournament_class add constraint FK78e4gyb2n3nahl2de4ex9c9qp foreign key (T_ID) references tournament;
alter table tournament_group add constraint FKte22s1nwj63gybkq0lfvn0vyx foreign key (GP_ID) references group_phase;
alter table tournament_player add constraint FKckudad7hjiry453vbbtsj3ql9 foreign key (association_id) references association;
alter table tournament_player add constraint FKiogds7xpq7tbscr9rlcgto05j foreign key (club_id) references club;
alter table TOURNAMENT_SINGLE_GAME add constraint FKnyl2ic1enqd5gq03biksl16pq foreign key (GAME_QUEUE_ID) references GAME_QUEUE;
alter table TOURNAMENT_SINGLE_GAME add constraint FKpsrfvitcw0ku88tvltj9hfqko foreign key (group_id) references tournament_group;
alter table TOURNAMENT_SINGLE_GAME add constraint FKox6oe5yfn631dkf7sj8uis938 foreign key (NEXT_GAME_ID) references TOURNAMENT_SINGLE_GAME;
alter table TOURNAMENT_SINGLE_GAME add constraint FK_P1 foreign key (player1_id) references tournament_player;
alter table TOURNAMENT_SINGLE_GAME add constraint FK_P2 foreign key (player2_id) references tournament_player;
alter table TOURNAMENT_SINGLE_GAME add constraint FKlgis5bk304f6ka7v33y3k1o24 foreign key (ROUND_ID) references round;
alter table TOURNAMENT_SINGLE_GAME_SET add constraint FKcp88fdy2kinrta57sji3byaye foreign key (SETS_ID) references GAME_SET;
alter table TOURNAMENT_SINGLE_GAME_SET add constraint FKqv165vg5rkcjouv8lx0p4gon0 foreign key (TOURNAMENT_SINGLE_GAME_ID) references TOURNAMENT_SINGLE_GAME;
alter table user add constraint FKmhhj09rh4m7qyavphtlx12j49 foreign key (TOURNAMENT_ID) references tournament;
