
    create table tournament_player  (
        id bigint generated by default as identity (start with 1),
        birthday date,
        email varchar(255),
        firstName varchar(255) not null,
        gender integer,
        lastName varchar(255) not null,
        mobileNumber varchar(255),
        qTtr integer,
        ttr integer,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity (start with 1),
        avatar binary(255),
        email varchar(255),
        locale varchar(255),
        locked boolean not null,
        loginName varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        type integer,
        primary key (id)
    );

    create table user_role (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    );
