
    create table tournament (
        id bigint generated by default as identity (start with 1),
        name varchar(255) not null,
        primary key (id)
    );

    create table tournament_class (
        id bigint generated by default as identity (start with 1),
        name varchar(255) not null,
        TC_ID bigint,
        primary key (id)
    );

    create table tournament_player (
        id bigint generated by default as identity (start with 1),
        birthday date,
        email varchar(255),
        firstname varchar(255) not null,
        gender varchar(1),
        lastname varchar(255) not null,
        mobilenumber varchar(255),
        qttr integer,
        ttr integer,
        TP_ID bigint,
        primary key (id)
    );

    create table user (
        id bigint generated by default as identity (start with 1),
        avatar varbinary(255),
        email varchar(255),
        locale varchar(255),
        locked boolean not null,
        loginname varchar(255) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        type integer,
        primary key (id)
    );

    create table user_role (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    );

    alter table tournament_class 
        add constraint FK_b4fgih2m95rr1y3afh8w5539j 
        foreign key (TC_ID) 
        references tournament;

    alter table tournament_player 
        add constraint FK_9l2i9dg2v7samg8vwjipt0my5 
        foreign key (TP_ID) 
        references tournament_class;
